version: "3.9"

services:
  db:
    image: postgres:15
    container_name: chore_db
    restart: always # auto restart on crash, reboot, or engine restart
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    volumes:
      - ./db-data:/var/lib/postgresql/data # persistent storage

  backend:
    build: ./backend
    container_name: chore_backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: todo_db
      PORT: 5000
    depends_on:
      - db
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      args:
        VITE_BASE_PATH: / # ensures Vite builds for root
    container_name: chore_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
# port 80 is mapped to apache. ->sudo lsof -i :80
